### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tinywombat765** [pcwalton/rust-media#32]
When I try to build the library I get
g++: error: /home/zethra/rust-media/target/debug/build/rust-media-4f16ffe1a06b74e6/out/../../libwebm-sys-8601c49ada690de1/out: No such file or directory

**Comment by est31** [comment]
I think #33 fixes this.

**Comment by est31** [comment]
Hmm, there is still a race condition. I think I'll file a PR for it.
