### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by yohaia** [pcwalton/rust-media#36]
when trying to run "cargo build" on the example folder,
I am getting this error 6 times:
error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)

any help will be appreciated

**Comment by jdm** [comment]
You need to use a nightly compiler.

**Comment by jdm** [comment]
Actually, this is a problem caused by a dependency of rust-media - the lewton crate uses the ieee754 crate, and that crate was broken as described in https://github.com/rust-lang/rust/issues/40470#issuecomment-295313690 .

**Comment by est31** [comment]
I've filed #37 to fix this. Sorry for the trouble!
